ok

diff --git a/.github/workflows/macos_x64.yml b/.github/workflows/macos_x64.yml
--- a/.github/workflows/macos_x64.yml
+++ b/.github/workflows/macos_x64.yml
@@ -58,20 +58,29 @@ jobs:
         rm -rf build
         rm -rf dist
         rm -rf app.spec
-        pyinstaller QtEsayDesigner_mac.spec
+        pyinstaller QtEasyDesigner_mac.spec
     - name: Create Zip Package # 创建压缩包
       run: |
         cd ./dist
-        zip -r ./QtEsayDesigner_MacOS.zip ./QtEsayDesigner.app
+        zip -r ./QtEasyDesigner_MacOS.zip ./QtEasyDesigner.app
+    - name: Run App Test # 运行程序检查是否返回 app run success
+      run: |
+          ./dist/my_app.app/Contents/MacOS/QtEasyDesigner test
+          if [ $? -eq 0 ]; then
+            echo "app run success"
+          else
+            echo "app run failed"
+            exit 1
+          fi
     - name: Upload Artifact # 上传构建产物，这里我们的源码目录是根目录，而实际运行的代码是构建后的 dist 目录
       uses: actions/upload-artifact@v3
       with:
         name: MacOS_x64
-        path: ./dist/QtEsayDesigner_MacOS.zip # 上传 dist 目录下的 app 执行文件
+        path: ./dist/QtEasyDesigner_MacOS.zip # 上传 dist 目录下的 app 执行文件
 
     - uses: ncipollo/release-action@v1 # 发布版本
       with:
         allowUpdates: true
-#        tag: "latest"
+        bodyFile: ./版本描述.md
         artifacts: "dist/*.zip"
         token: ${{ secrets.GITHUB_TOKEN }}
